create table if not exists public.document_chunks (
    id bigint generated by default as identity primary key,
    doc_id text not null,
    chunk_id text not null,
    chunk_text text not null,
    chunk_vector vector not null,
    created_timestamp timestamptz default now(),
    last_updated timestamptz default now(),
    constraint document_chunks_doc_id_fkey
        foreign key (doc_id) references public.documents(doc_id) on delete cascade
);
