from enum import StrEnum


class ScopeType(StrEnum):
    FEATURE = "FEATURE"
    USER_STORY = "USER_STORY"


class RequirementType(StrEnum):
    COMPONENT_EXISTENCE = "COMPONENT_EXISTENCE"
    EXECUTION_PATH = "EXECUTION_PATH"
    API_CONTRACT = "API_CONTRACT"
    DATA_PERSISTENCE = "DATA_PERSISTENCE"
    DATABASE_CHANGE = "DATABASE_CHANGE"
    CONFIGURATION = "CONFIGURATION"
    DEPENDENCY = "DEPENDENCY"
    TEST_COVERAGE = "TEST_COVERAGE"
    SECURITY = "SECURITY"
    NON_FUNCTIONAL = "NON_FUNCTIONAL"
    OTHER = "OTHER"


class RequirementApplicability(StrEnum):
    STATICALLY_VERIFIABLE = "STATICALLY_VERIFIABLE"
    RUNTIME_EVIDENCE_REQUIRED = "RUNTIME_EVIDENCE_REQUIRED"
    EXTERNAL_EVIDENCE_REQUIRED = "EXTERNAL_EVIDENCE_REQUIRED"


class FindingStatus(StrEnum):
    PRESENT = "PRESENT"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"


class ReasonCode(StrEnum):
    IMPLEMENTED = "IMPLEMENTED"
    PARTIAL_IMPLEMENTATION = "PARTIAL_IMPLEMENTATION"
    PARTIAL_EXECUTION_PATH = "PARTIAL_EXECUTION_PATH"
    NO_IMPLEMENTATION_EVIDENCE = "NO_IMPLEMENTATION_EVIDENCE"
    CONTRADICTORY_EVIDENCE = "CONTRADICTORY_EVIDENCE"
    INSUFFICIENT_STATIC_EVIDENCE = "INSUFFICIENT_STATIC_EVIDENCE"
    RETRIEVAL_COVERAGE_INCOMPLETE = "RETRIEVAL_COVERAGE_INCOMPLETE"
    UNSUPPORTED_LANGUAGE = "UNSUPPORTED_LANGUAGE"
    RUNTIME_VALIDATION_REQUIRED = "RUNTIME_VALIDATION_REQUIRED"
    EXTERNAL_SYSTEM_EVIDENCE_REQUIRED = "EXTERNAL_SYSTEM_EVIDENCE_REQUIRED"


class EvidenceType(StrEnum):
    SOURCE_CODE = "SOURCE_CODE"
    TEST = "TEST"
    CONFIGURATION = "CONFIGURATION"
    DATABASE_MIGRATION = "DATABASE_MIGRATION"
    DEPENDENCY = "DEPENDENCY"
    ARCHITECTURE_DOCUMENT = "ARCHITECTURE_DOCUMENT"
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"
    GRAPH_PATH = "GRAPH_PATH"
    RETRIEVAL_TRACE = "RETRIEVAL_TRACE"
    REPOSITORY_SUMMARY = "REPOSITORY_SUMMARY"


class EvidenceDirection(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    CONTEXT = "CONTEXT"
    SEARCHED_NO_MATCH = "SEARCHED_NO_MATCH"


class RetrievalMethod(StrEnum):
    STRUCTURED_SYMBOL = "STRUCTURED_SYMBOL"
    STRUCTURED_API = "STRUCTURED_API"
    STRUCTURED_SCHEMA = "STRUCTURED_SCHEMA"
    STRUCTURED_TEST = "STRUCTURED_TEST"
    KEYWORD_FTS = "KEYWORD_FTS"
    VECTOR = "VECTOR"
    GRAPH = "GRAPH"
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"
    REPOSITORY_SUMMARY = "REPOSITORY_SUMMARY"
    HYBRID = "HYBRID"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AnalysisStage(StrEnum):
    SCOPE_RESOLUTION = "SCOPE_RESOLUTION"
    REQUIREMENT_LOADING = "REQUIREMENT_LOADING"
    DESIGN_CONTEXT = "DESIGN_CONTEXT"
    REQUIREMENT_DECOMPOSITION = "REQUIREMENT_DECOMPOSITION"
    EXPECTED_GRAPH = "EXPECTED_GRAPH"
    GITHUB_SNAPSHOT = "GITHUB_SNAPSHOT"
    SOURCE_PARSING = "SOURCE_PARSING"
    SOURCE_INDEXING = "SOURCE_INDEXING"
    ACTUAL_GRAPH = "ACTUAL_GRAPH"
    EVIDENCE_RETRIEVAL = "EVIDENCE_RETRIEVAL"
    CONTEXT_BUILDING = "CONTEXT_BUILDING"
    LLM_COMPARISON = "LLM_COMPARISON"
    CLASSIFICATION = "CLASSIFICATION"
    SCORING = "SCORING"
    PERSISTING = "PERSISTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class PredicateResult(StrEnum):
    PROVEN = "PROVEN"
    NOT_PROVEN = "NOT_PROVEN"
    CONTRADICTED = "CONTRADICTED"
    UNKNOWN = "UNKNOWN"


class ImpactCategory(StrEnum):
    FUNCTIONAL = "FUNCTIONAL"
    PERFORMANCE = "PERFORMANCE"
    SECURITY = "SECURITY"
    RELIABILITY = "RELIABILITY"
    DATA = "DATA"
    INTEGRATION = "INTEGRATION"
    TESTING = "TESTING"
    RELEASE = "RELEASE"
    DEPENDENCY = "DEPENDENCY"
    OPERATIONAL = "OPERATIONAL"


class GraphNodeType(StrEnum):
    FEATURE = "FEATURE"
    USER_STORY = "USER_STORY"
    REQUIREMENT = "REQUIREMENT"
    REPOSITORY = "REPOSITORY"
    REPOSITORY_SNAPSHOT = "REPOSITORY_SNAPSHOT"
    FILE = "FILE"
    CLASS = "CLASS"
    FUNCTION = "FUNCTION"
    API = "API"
    SERVICE = "SERVICE"
    COMPONENT = "COMPONENT"
    DATABASE = "DATABASE"
    TEST = "TEST"
    DEPENDENCY = "DEPENDENCY"
    DOCUMENT = "DOCUMENT"
    DOCUMENT_CHUNK = "DOCUMENT_CHUNK"


class GraphRelationshipType(StrEnum):
    HAS_USER_STORY = "HAS_USER_STORY"
    HAS_REQUIREMENT = "HAS_REQUIREMENT"
    REQUIRES = "REQUIRES"
    HAS_SNAPSHOT = "HAS_SNAPSHOT"
    CONTAINS_FILE = "CONTAINS_FILE"
    DEFINES = "DEFINES"
    DECLARES_API = "DECLARES_API"
    IMPORTS = "IMPORTS"
    CALLS = "CALLS"
    USES = "USES"
    IMPLEMENTED_BY = "IMPLEMENTED_BY"
    TESTED_BY = "TESTED_BY"
    HAS_DOCUMENT = "HAS_DOCUMENT"
    HAS_CHUNK = "HAS_CHUNK"
    MENTIONS = "MENTIONS"
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"


class GeneratedChangeStatus(StrEnum):
    REQUESTED = "REQUESTED"
    GENERATING = "GENERATING"
    GENERATED = "GENERATED"
    VALIDATING = "VALIDATING"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PR_CREATED = "PR_CREATED"
    MERGED = "MERGED"
    FAILED = "FAILED"
