begin;

create extension if not exists vector;

alter table public.documents
    add column if not exists product_space_id uuid,
    add column if not exists project_id uuid,
    add column if not exists release_id uuid,
    add column if not exists environment_id text,
    add column if not exists storage_uri text,
    add column if not exists mime_type text,
    add column if not exists file_size_bytes bigint,
    add column if not exists file_checksum text,
    add column if not exists parser_name text,
    add column if not exists parser_version text,
    add column if not exists page_count integer,
    add column if not exists ingestion_error_code text,
    add column if not exists ingestion_error text,
    add column if not exists ingestion_metadata jsonb not null default '{}'::jsonb,
    add column if not exists created_by text;

alter table public.documents
    alter column doc_raw_text set default '';

alter table public.documents
    drop constraint if exists documents_doc_status_check;

alter table public.documents
    add constraint documents_doc_status_check
    check (
        doc_status in (
            'RECEIVED',
            'UPLOADED',
            'PARSING',
            'PARSED',
            'CHUNKING',
            'CHUNKED',
            'EMBEDDING',
            'EMBEDDED',
            'FAILED'
        )
    );

alter table public.documents
    drop constraint if exists documents_product_space_id_fkey,
    add constraint documents_product_space_id_fkey
        foreign key (product_space_id)
        references public.product_spaces(id),
    drop constraint if exists documents_project_id_fkey,
    add constraint documents_project_id_fkey
        foreign key (project_id)
        references public.projects(id),
    drop constraint if exists documents_release_id_fkey,
    add constraint documents_release_id_fkey
        foreign key (release_id)
        references public.releases(id);

alter table public.document_chunks
    add column if not exists product_space_id uuid,
    add column if not exists project_id uuid,
    add column if not exists release_id uuid,
    add column if not exists environment_id text,
    add column if not exists chunk_index integer,
    add column if not exists token_count integer,
    add column if not exists page_numbers integer[],
    add column if not exists section_path text[],
    add column if not exists chunk_metadata jsonb not null default '{}'::jsonb,
    add column if not exists embedding_model text,
    add column if not exists embedding_dimensions integer,
    add column if not exists embedding_status text not null default 'PENDING';

alter table public.document_chunks
    drop constraint if exists document_chunks_embedding_status_check;

alter table public.document_chunks
    add constraint document_chunks_embedding_status_check
    check (embedding_status in ('PENDING', 'COMPLETED', 'FAILED'));

create table if not exists public.document_ingestion_events (
    id bigint generated by default as identity primary key,
    document_id text not null
        references public.documents(doc_id) on delete cascade,
    product_space_id uuid not null
        references public.product_spaces(id),
    project_id uuid not null
        references public.projects(id),
    stage text not null,
    status text not null,
    attempt integer not null default 1,
    message text,
    details jsonb not null default '{}'::jsonb,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    constraint document_ingestion_events_status_check
        check (status in ('RUNNING', 'COMPLETED', 'FAILED'))
);

create table if not exists public.document_ingestion_jobs (
    id bigint generated by default as identity primary key,
    document_id text not null
        references public.documents(doc_id) on delete cascade,
    requested_stage text not null default 'PARSING',
    status text not null default 'PENDING',
    attempt integer not null default 1,
    available_at timestamptz not null default now(),
    locked_at timestamptz,
    locked_by text,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint document_ingestion_jobs_status_check
        check (status in ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED'))
);

create index if not exists idx_documents_project_scope
    on public.documents (
        product_space_id,
        project_id,
        release_id,
        environment_id
    );

create index if not exists idx_documents_project_status
    on public.documents (product_space_id, project_id, doc_status);

create unique index if not exists idx_documents_scope_checksum
    on public.documents (product_space_id, project_id, file_checksum)
    where doc_status <> 'FAILED' and file_checksum is not null;

create index if not exists idx_document_chunks_project_scope
    on public.document_chunks (
        product_space_id,
        project_id,
        release_id,
        environment_id
    );

create unique index if not exists idx_document_chunks_document_index
    on public.document_chunks (doc_id, chunk_index)
    where chunk_index is not null;

create index if not exists idx_ingestion_events_document
    on public.document_ingestion_events (document_id, created_at);

create index if not exists idx_ingestion_jobs_claim
    on public.document_ingestion_jobs (status, available_at);

commit;
